/**
 * Image view/angle type for comprehensive product understanding
 */
export type ImageViewType = 
  | 'main'           // Primary product image
  | 'front'          // Front view
  | 'back'           // Back view
  | 'side'           // Side view (left or right)
  | 'detail'         // Close-up detail shot
  | 'alternate'      // Alternate angle
  | 'zoom'           // High-resolution zoom image
  | 'lifestyle'      // Product in use/lifestyle context
  | 'unknown';       // Cannot determine view type

/**
 * Comprehensive metadata for each downloaded product image
 */
export interface ImageMetadata {
  localPath: string;           // Local file path
  originalUrl: string;         // Original source URL
  width: number;               // Image width in pixels
  height: number;              // Image height in pixels
  fileSize: number;            // File size in bytes
  format: string;              // Image format (png, jpg, webp, etc.)
  viewType: ImageViewType;     // Type of view/angle
  qualityScore: number;        // Quality score (0-100) based on resolution and size
  isMainProductImage: boolean; // Whether this is the primary product image
  sourceLocation?: string;     // Where on the page this image was found
  downloadedAt: Date;          // When the image was downloaded
}

/**
 * Product data extracted from a product page
 */
export interface ProductData {
  url: string;
  name: string;
  description: string;
  images: string[];                    // Original image URLs from the page
  localImagePaths: string[];           // Downloaded local file paths for AI generation
  imageMetadata: ImageMetadata[];      // Comprehensive metadata for each downloaded image
  price?: string;
  category?: string;
  brand?: string;
  extractedAt: Date;
}

/**
 * Design brief generated by LLM
 */
export interface DesignBrief {
  productName: string;
  visualStyle: string;
  messaging: string;
  targetAudience: string;
  colorPalette: string[];
  mood: string;
  keyFeatures: string[];
  callToAction: string;
  imagePrompt: string;
  videoPrompt?: string;
  generatedAt: Date;
}

/**
 * Generated asset (image or video)
 */
export interface GeneratedAsset {
  id: string;
  jobId: string;
  type: 'image' | 'video';
  url: string;
  filePath: string;
  title: string;
  description: string;
  thumbnail?: string;
  metadata: AssetMetadata;
  createdAt: Date;
}

/**
 * Asset metadata
 */
export interface AssetMetadata {
  width?: number;
  height?: number;
  duration?: number;
  format: string;
  size: number;
}

/**
 * Generation job status
 */
export type JobStatus = 
  | 'pending' 
  | 'scraping' 
  | 'generating_brief' 
  | 'generating_assets' 
  | 'completed' 
  | 'failed';

/**
 * Generation job tracking
 */
export interface GenerationJob {
  id: string;
  productUrl: string;
  status: JobStatus;
  progress: number;
  currentStep: string;
  productData?: ProductData;
  designBrief?: DesignBrief;
  assets: GeneratedAsset[];
  error?: string;
  createdAt: Date;
  completedAt?: Date;
}
