/**
 * Image view/angle type for comprehensive product understanding
 */
export type ImageViewType = 
  | 'main'           // Primary product image
  | 'front'          // Front view
  | 'back'           // Back view
  | 'side'           // Side view (left or right)
  | 'detail'         // Close-up detail shot
  | 'alternate'      // Alternate angle
  | 'zoom'           // High-resolution zoom image
  | 'lifestyle'      // Product in use/lifestyle context
  | 'unknown';       // Cannot determine view type

/**
 * Comprehensive metadata for each downloaded product image
 */
export interface ImageMetadata {
  localPath: string;           // Local file path
  originalUrl: string;         // Original source URL
  width: number;               // Image width in pixels
  height: number;              // Image height in pixels
  fileSize: number;            // File size in bytes
  format: string;              // Image format (png, jpg, webp, etc.)
  viewType: ImageViewType;     // Type of view/angle
  qualityScore: number;        // Quality score (0-100) based on resolution and size
  isMainProductImage: boolean; // Whether this is the primary product image
  sourceLocation?: string;     // Where on the page this image was found
  downloadedAt: Date;          // When the image was downloaded
}

/**
 * Product data extracted from a product page
 */
export interface ProductData {
  url: string;
  name: string;
  description: string;
  images: string[];                    // Original image URLs from the page
  localImagePaths: string[];           // Downloaded local file paths for AI generation
  imageMetadata: ImageMetadata[];      // Comprehensive metadata for each downloaded image
  price?: string;
  category?: string;
  brand?: string;
  extractedAt: Date;
}

/**
 * Editorial Image Brief Structure (full JSON format)
 */
export interface EditorialImageBrief {
  campaign_meta: {
    project_name: string;
    brand_identity: string;
    platform_use_case: string;
    target_audience: {
      persona: string;
      emotional_driver: string;
    };
  };
  brand_gravity_profile: {
    brand_energy_level: string;
    attitude: string;
    risk_tolerance: string;
    visual_gravity: string;
    references: string[];
  };
  editorial_constraints: {
    image_type: string;
    avoid_commercial_aesthetics: boolean;
    allowed_imperfection_level: string;
    authenticity_bias: string;
  };
  creative_concept: {
    core_mood: string;
    narrative_theme: string;
    editorial_statement: string;
  };
  visual_hierarchy: {
    primary_subject: string;
    secondary_subjects: string[];
    frame_dominance: {
      primary_subject_percentage: string;
      secondary_subject_percentage: string;
    };
  };
  product_focus: {
    key_items: Array<{
      product_name: string;
      category: string;
      colorway_or_variant: string;
    }>;
    visibility_style: string;
    interaction_type: string;
  };
  camera_and_composition: {
    camera_angle: string;
    lens_feel: string;
    composition_style: string;
    depth_of_field: string;
  };
  setting_and_environment: {
    location_type: string;
    environmental_drama: string[];
    time_of_day: string;
  };
  lifestyle_semantic_controls: {
    positive_signals: string[];
    negative_signals: string[];
  };
  artistic_license: {
    reality_bending_allowed: boolean;
    surreal_elements: string[];
    symbolism_notes: string;
  };
  text_and_text_visual: {
    include_text: boolean;
    text_content: {
      headline: string;
      supporting_line: string;
    };
    text_intent: string;
    typography_style: {
      font_character: string;
      case_usage: string;
      weight: string;
    };
    text_placement: {
      position: string;
      interaction_with_subject: string;
      safe_area_rule: string;
    };
    text_visual_treatment: {
      color: string;
      effects: string;
      integration_style: string;
    };
  };
  post_production: {
    color_grading: string;
    texture_treatment: string;
    final_mood_check: string;
  };
}

/**
 * Design brief generated by LLM
 */
export interface DesignBrief {
  productName: string;
  visualStyle: string;
  messaging: string;
  targetAudience: string;
  colorPalette: string[];
  mood: string;
  keyFeatures: string[];
  callToAction: string;
  imagePrompt: string;
  videoPrompt?: string;
  editorialBrief?: EditorialImageBrief; // Full JSON editorial brief
  generatedAt: Date;
}

/**
 * Generated asset (image or video)
 */
export interface GeneratedAsset {
  id: string;
  jobId: string;
  type: 'image' | 'video';
  url: string;
  filePath: string;
  title: string;
  description: string;
  thumbnail?: string;
  metadata: AssetMetadata;
  createdAt: Date;
}

/**
 * Asset metadata
 */
export interface AssetMetadata {
  width?: number;
  height?: number;
  duration?: number;
  format: string;
  size: number;
}

/**
 * Generation job status
 */
export type JobStatus = 
  | 'pending' 
  | 'scraping' 
  | 'generating_brief' 
  | 'generating_assets' 
  | 'completed' 
  | 'failed';

/**
 * Generation job tracking
 */
export interface GenerationJob {
  id: string;
  productUrl: string;
  status: JobStatus;
  progress: number;
  currentStep: string;
  productData?: ProductData;
  designBrief?: DesignBrief;
  assets: GeneratedAsset[];
  error?: string;
  createdAt: Date;
  completedAt?: Date;
}
