/**
 * Product data extracted from a product page
 */
export interface ProductData {
  url: string;
  name: string;
  description: string;
  images: string[];
  price?: string;
  category?: string;
  brand?: string;
  extractedAt: Date;
}

/**
 * Design brief generated by LLM
 */
export interface DesignBrief {
  productName: string;
  visualStyle: string;
  messaging: string;
  targetAudience: string;
  colorPalette: string[];
  mood: string;
  keyFeatures: string[];
  callToAction: string;
  imagePrompt: string;
  videoPrompt?: string;
  generatedAt: Date;
}

/**
 * Generated asset (image or video)
 */
export interface GeneratedAsset {
  id: string;
  jobId: string;
  type: 'image' | 'video';
  url: string;
  filePath: string;
  title: string;
  description: string;
  thumbnail?: string;
  metadata: AssetMetadata;
  createdAt: Date;
}

/**
 * Asset metadata
 */
export interface AssetMetadata {
  width?: number;
  height?: number;
  duration?: number;
  format: string;
  size: number;
}

/**
 * Generation job status
 */
export type JobStatus = 
  | 'pending' 
  | 'scraping' 
  | 'generating_brief' 
  | 'generating_assets' 
  | 'completed' 
  | 'failed';

/**
 * Generation job tracking
 */
export interface GenerationJob {
  id: string;
  productUrl: string;
  status: JobStatus;
  progress: number;
  currentStep: string;
  productData?: ProductData;
  designBrief?: DesignBrief;
  assets: GeneratedAsset[];
  error?: string;
  createdAt: Date;
  completedAt?: Date;
}
